;ALP TO FIND COMPLEMENT OF 16-BIT NUMBER

START:
;CLEAR REGISTERS
MOV R0, #00
MOV R1, #00
MOV R2, #00
MOV R3, #00
MOV R4, #00

;LOAD DATA INTO REGISTERS
MOV R1, #00H
MOV R2, #00H

;FIND THE 2'S COMPLEMENT
MOV A, R2
CPL A			;1'S COMPLEMENT LOWER BYTE
MOV R4, A
MOV A, R1
CPL A			;1'S COMPLEMENT HIGHER BYTE
MOV R3, A
MOV A, R4
ADD A, #01H		;2'S COMPLEMENT LOWER BYTE
JNC SKIP

MOV A, R3		;IF CARRY OCCURS IN LOWER BYTE, ADD TO HIGHER BYTE
INC A
MOV R3, A

SKIP:			;PUT CORRECT LOWER BYTE
MOV R4, A

HALT: 
SJMP HALT
